// flow-typed signature: c079c017ab70d21427aacf858f5f3ef8
// flow-typed version: <<STUB>>/@callstack/eslint-config_v^3.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@callstack/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@callstack/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@callstack/eslint-config/index' {
  declare module.exports: $Exports<'@callstack/eslint-config'>;
}
declare module '@callstack/eslint-config/index.js' {
  declare module.exports: $Exports<'@callstack/eslint-config'>;
}
