/* @flow */

export const START_CREATING_CANDIDATE = 'START_CREATING_CANDIDATE';
export const SUCCESS_CREATING_CANDIDATE = 'SUCCESS_CREATING_CANDIDATE';
export const FAILURE_CREATING_CANDIDATE = 'FAILURE_CREATING_CANDIDATE';
export const CLEAR_CANDIDATE_MESSAGE = 'CLEAR_CANDIDATE_MESSAGE';

export const START_CANDIDATES_FETCHING = 'START_CANDIDATES_FETCHING';
export const SUCCESS_CANDIDATES_FETCHING = 'SUCCESS_CANDIDATES_FETCHING';
export const FAILURE_CANDIDATES_FETCHING = 'FAILURE_CANDIDATES_FETCHING';

export const START_CREATING_ELECTION = 'START_CREATING_ELECTION';
export const SUCCESS_CREATING_ELECTION = 'SUCCESS_CREATING_ELECTION';
export const FAILURE_CREATING_ELECTION = 'FAILURE_CREATING_ELECTION';
export const CLEAR_ELECTIONS_MESSAGE = 'CLEAR_ELECTIONS_MESSAGE';

export const START_ELECTIONS_FETCHING = 'START_ELECTIONS_FETCHING';
export const SUCCESS_ELECTIONS_FETCHING = 'SUCCESS_ELECTIONS_FETCHING';
export const FAILURE_ELECTIONS_FETCHING = 'FAILURE_ELECTIONS_FETCHING';

export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAILURE_LOGIN = 'FAILURE_LOGIN';

export const CREDENTIALS_RETRIEVED = 'CREDENTIALS_RETRIEVED';
export const CREDENTIALS_REMOVED = 'CREDENTIALS_REMOVED';
export const FAILURE_CREDENTIALS_RETRIEVE = 'FAILURE_CREDENTIALS_RETRIEVE';

export const START_MAKING_VOTE = 'START_MAKING_VOTE';
export const SUCCESS_MAKING_VOTE = 'SUCCESS_MAKING_VOTE';
export const FAILURE_MAKING_VOTE = 'FAILURE_MAKING_VOTE';
export const CLEAR_VOTE_MESSAGE = 'CLEAR_VOTE_MESSAGE';

export const START_FETCHING_STATISTICS = 'START_FETCHING_STATISTICS';
export const SUCCESS_FETCHING_STATISTICS = 'SUCCESS_FETCHING_STATISTICS';
export const FAILURE_FETCHING_STATISTICS = 'FAILURE_FETCHING_STATISTICS';
