/* @flow */

export const START_CREATING_CANDIDATE = 'START_CREATING_CANDIDATE';
export const SUCCESS_CREATING_CANDIDATE = 'SUCCESS_CREATING_CANDIDATE';
export const FAILURE_CREATING_CANDIDATE = 'FAILURE_CREATING_CANDIDATE';

export const START_CANDIDATES_FETCHING = 'START_CANDIDATES_FETCHING';
export const SUCCESS_CANDIDATES_FETCHING = 'SUCCESS_CANDIDATES_FETCHING';
export const FAILURE_CANDIDATES_FETCHING = 'FAILURE_CANDIDATES_FETCHING';
